Add warm start
kul-forbes/QPALM.jl pull request #1
Opened 2019-05-28 16:06 UTC by WimVanRoy

- Added the warm_start functionality to the wrapper
- Added a .gitignore file for the automatically generated files
- Added simple tests for the warm_start functionality

2019-05-28 18:34 UTC, lostella approved these changes
Looks good to me, thanks.

We could test that the warm starting actually takes place, by e.g. initializing the iterates from a previously computed solution and checking that 0 iterations take place.

But this already looks fine.

2019-05-28 18:34 UTC, lostella commented on test/warm_start.jl
> +    act = 3
`act` can probably be removed here

2019-05-29 06:52 UTC, WimVanRoy commented
Ok, I improved the testing but it turns out that if you re-create the model and reuse x & y, you only need less iterations (f.ex. from 10 -> 5). This is probably due to the stop criteria that are updated each cycle. 
Only when you can reuse the same model-data, the number of iterations are equal to 1.

2019-05-29 07:25 UTC, lostella commented
Just fix the random seed, then we can merge. Thank you!

2019-05-29 12:19 UTC, lostella requested changes

2019-05-29 12:19 UTC, lostella commented on test/warm_start.jl
> +
It’s better to do

```suggestion
using Random

Random.seed!(0)
```

here, to make this test less shaky.

2019-05-29 16:39 UTC, merged

2019-05-29 16:39 UTC, WimVanRoy commented on test/warm_start.jl
> +
I do agree, thank you for the comment!